### ISSUE TITLE
Fail integration if TestFlight upload does not succeed?

### ISSUE THREAD

**Issue by pkamb** [drewcrawford/CaveJohnson#19] opened 2015-04-22 00:55 UTC
Do you happen to know if it's possible to Fail the Xcode Bot integration in the post-integration Run Script phase?

I'm finding it annoying to see that my `testflight` bot "passes", but then that the TestFlight upload did not actually happen.

**Comment by drewcrawford** [comment] 2015-04-22 01:12
I'm not aware of anything to do it.  File a dupe of

![screen shot 2015-04-21 at 8 12 11 pm](https://cloud.githubusercontent.com/assets/183400/7265649/c02d68a0-e862-11e4-87aa-a6c34ead0af4.png)

**Comment by drewcrawford** [comment] 2015-04-22 01:18
Now that I think about it, it probably is possible to beat this for pre-integration triggers.  You would create a "run build script" phase in Xcode that looks for information from the trigger in e.g. an environment variable.  Terrible, but it would work.

For post-integration triggers, like testflight in your example, that trick wouldn't work.

**Comment by pkamb** [comment] 2015-04-23 18:13
duped as rdar://20670278

**Comment by drewcrawford** [comment] 2015-06-11 09:40
XC7 fails an integration when a trigger script fails.

![screen shot 2015-06-11 at 4 39 43 am](https://cloud.githubusercontent.com/assets/183400/8104126/eb5abdb2-0ff3-11e5-8f2b-6806d94a73e6.png)

Closing since upstream fixed.

**Closed by drewcrawford** 2015-06-11 09:40 UTC
Labels: radar

**Comment by pkamb** [comment] 2015-06-11 16:01
I talked to the Xcode folks at the WWDC labs and was excited to hear about this new Xcode 7 feature :+1:
